insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES I',36,7,16,14,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES III',36,7,16,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('MPCT',36,7,16,17,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES IV',36,7,16,17,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES V',36,7,16,18,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES I',36,7,14,14,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES III',36,7,14,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('MPCT',36,7,14,17,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES IV',36,7,14,17,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES V',36,7,14,18,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES VI',36,7,14,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES VI',36,7,16,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SEG INF',38,7,16,18,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SEG INF',38,7,14,18,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES II',39,7,16,15,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES II',39,7,14,15,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SOC TEC',40,7,16,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SOC TEC',40,7,14,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('IHC',43,7,16,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('IHC',43,7,14,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ECON FIN',44,7,16,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ECON FIN',44,7,14,16,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('CONTAB',49,7,16,15,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('CONTAB',49,7,14,15,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LAB HARD',51,7,16,14,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LAB HARD',51,7,14,14,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('COM EXP',37,7,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('COM EXP',37,7,14,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('A O COMP',38,7,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SIST INF',38,7,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('A O COMP',38,7,14,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SIST INF',38,7,14,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ENG SOFT I',41,7,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ENG SOFT II',53,7,16,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ENG SOFT I',41,7,14,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ENG SOFT II',53,7,14,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ALG L P',42,7,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ALG L P',42,7,14,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ENG SOFT III',43,7,16,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('P DISP MO',43,7,16,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ENG SOFT III',43,7,14,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('P DISP MO',43,7,14,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG M I',47,7,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('BD',47,7,16,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LAB BD',47,7,16,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG M I',47,7,14,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('BD',47,7,14,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LAB BD',47,7,14,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG WEB',60,7,16,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG WEB',60,7,14,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('MAT DISC',48,7,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('CALCULO',48,7,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG LIN',48,7,16,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('MAT DISC',48,7,14,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('CALCULO',48,7,14,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG LIN',48,7,14,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG O O',50,7,16,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LAB ENG SOFT',50,7,16,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROG O O',50,7,14,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LAB ENG SOFT',50,7,14,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('IA',50,7,14,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('IA',50,7,16,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SO I',51,7,16,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SO II',51,7,16,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('REDES COMP',51,7,16,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SO I',51,7,14,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('SO II',51,7,14,17,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('REDES COMP',51,7,14,18,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LING PROG',61,7,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LING PROG',61,7,14,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ADM GERAL',56,7,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ADM GERAL',56,7,14,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ED',57,7,16,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ED',57,7,14,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ESTAT AP',58,7,16,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ESTAT AP',58,7,14,16,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('GEST E GOV',43,7,16,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('GEST E GOV',43,7,14,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ETICA',46,7,14,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ETICA',46,7,16,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('GEST PROJ',52,7,16,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('GEST PROJ',52,7,14,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('TOP ESPECIAIS',53,7,14,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('TOP ESPECIAIS',53,7,16,19,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('GEST EQUIP',56,7,14,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('GEST EQUIP',56,7,16,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('EMPREEND',56,7,14,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('EMPREEND',56,7,16,19,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES I',39,8,16,14,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('INGLES II',39,8,16,15,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PI - GEST E INOV',52,8,16,14,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('COM EMP',45,8,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('CALCULO',48,8,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('EMP E INOV',56,8,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROSP B INF TEC',52,8,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ADM GERAL',54,8,16,14,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ESTATISTICA',59,8,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('ECONOMIA',44,8,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('LEGIS EMPR',46,8,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PI II',52,8,16,15,2);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('MARKETING',62,8,16,15,4);
insert into grade_horario_disciplinas (disciplina, id_professor_id, id_curso_id, id_periodo_id, id_semestre_id, carga_horaria) values ('PROSP NEG',62,8,16,15,4);
