insert into grade_horario_professores (professor) values ('Anna');
insert into grade_horario_professores (professor) values ('Carlos');
insert into grade_horario_professores (professor) values ('Carlos D');
insert into grade_horario_professores (professor) values ('Claudia');
insert into grade_horario_professores (professor) values ('Clóvis');
insert into grade_horario_professores (professor) values ('Cozin');
insert into grade_horario_professores (professor) values ('Doniseti');
insert into grade_horario_professores (professor) values ('Fabrício');
insert into grade_horario_professores (professor) values ('Fernandina');
insert into grade_horario_professores (professor) values ('Fernando');
insert into grade_horario_professores (professor) values ('Frachone');
insert into grade_horario_professores (professor) values ('Geraldo');
insert into grade_horario_professores (professor) values ('Júnior');
insert into grade_horario_professores (professor) values ('Leandro');
insert into grade_horario_professores (professor) values ('Lucas');
insert into grade_horario_professores (professor) values ('Marco');
insert into grade_horario_professores (professor) values ('Odair');
insert into grade_horario_professores (professor) values ('Plotze');
insert into grade_horario_professores (professor) values ('Rinaldo');
insert into grade_horario_professores (professor) values ('Sprovieri');
insert into grade_horario_professores (professor) values ('Suzana');
insert into grade_horario_professores (professor) values ('Takeda');
insert into grade_horario_professores (professor) values ('Valéria');
insert into grade_horario_professores (professor) values ('Viviane');
insert into grade_horario_professores (professor) values ('Jean');
insert into grade_horario_professores (professor) values ('Perez');
insert into grade_horario_professores (professor) values ('Livre - Vago');
