# Generated by Django 2.1.2 on 2018-12-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidades',
            fields=[
                ('id_disponibilidade', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.IntegerField()),
                ('sequencia', models.IntegerField()),
                ('segunda', models.BooleanField(verbose_name='Segunda-Feira')),
                ('terca', models.BooleanField(verbose_name='Terça-Feira')),
                ('quarta', models.BooleanField(verbose_name='Quarta-Feira')),
                ('quinta', models.BooleanField(verbose_name='Quinta-Feira')),
                ('sexta', models.BooleanField(verbose_name='Sexta-Feira')),
                ('sabado', models.BooleanField(verbose_name='Sábado')),
            ],
        ),
    ]
