# Generated by Django 2.1.2 on 2019-01-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.IntegerField()),
                ('sequencia', models.IntegerField()),
                ('segunda', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Segunda-Feira')),
                ('terca', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Terça-Feira')),
                ('quarta', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Quarta-Feira')),
                ('quinta', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Quinta-Feira')),
                ('sexta', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Sexta-Feira')),
                ('sabado', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Sábado')),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='disponibilidades',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Periodos'),
        ),
        migrations.AddField(
            model_name='disponibilidades',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Professores'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Periodos'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Professores'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Semestres'),
        ),
    ]
