# Generated by Django 2.1.2 on 2018-12-13 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id_dias', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidades',
            fields=[
                ('id_disponibilidade', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Cursos')),
                ('id_dias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Dias')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='disponibilidades',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Periodos'),
        ),
        migrations.AddField(
            model_name='disponibilidades',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Professores'),
        ),
        migrations.AddField(
            model_name='disponibilidades',
            name='id_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Semestres'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Periodos'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Professores'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade_horario.Semestres'),
        ),
    ]
