# Generated by Django 2.1.2 on 2019-01-30 23:36

from django.db import migrations


def carregar_dados_do_sql():
    # from django.conf import settings
    # import os
    # print(os.getcwd())
    # sql_statements = open('grade_horario/sql/professores.sql', 'r', encoding='utf-8', errors='ignore').read()
    sql_statements = open('grade_horario/sql/professores.sql', 'r', encoding='latin-1').read()
    return sql_statements


def limpar_tabela():
    return 'DELETE from grade_horario_professores;'

class Migration(migrations.Migration):

    dependencies = [
        ('grade_horario', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(carregar_dados_do_sql(), limpar_tabela())
    ]
