# Generated by Django 2.1.2 on 2019-02-03 23:51

from django.db import migrations


def carregar_sql_dados_semestre():
    sql_semestre = open('grade_horario/sql/semestre.sql', 'r').read()
    return sql_semestre


def limpar_tabela_semestre():
    return 'DELETE FROM grade_horario_semestres'

class Migration(migrations.Migration):

    dependencies = [
        ('grade_horario', '0002_CargaInicial_Prof'),
    ]

    operations = [
        migrations.RunSQL(carregar_sql_dados_semestre(), limpar_tabela_semestre())
    ]
