# Generated by Django 2.1.2 on 2019-02-03 23:59

from django.db import migrations


def carregar_sql_periodo():
    sql_periodo = open('grade_horario/sql/periodo.sql', 'r').read()
    return sql_periodo


def limpar_tabela_periodo():
    return 'DELETE FROM grade_horario_periodos'


class Migration(migrations.Migration):

    dependencies = [
        ('grade_horario', '0003_CargaInicial_Semetre'),
    ]

    operations = [
        migrations.RunSQL(carregar_sql_periodo(), limpar_tabela_periodo())
    ]
