# Generated by Django 2.1.2 on 2019-02-04 00:03

from django.db import migrations


def carregar_sql_dia():
    sql_dia = open('grade_horario/sql/diasN.sql', 'r').read()
    return sql_dia


def limpar_tabela_dia():
    return 'DELETE FROM grade_horario_dias'


class Migration(migrations.Migration):

    dependencies = [
        ('grade_horario', '0004_CargaInicial_Periodo'),
    ]

    operations = [
        migrations.RunSQL(carregar_sql_dia(), limpar_tabela_dia())
    ]
