# Generated by Django 2.1.2 on 2019-02-04 00:05

from django.db import migrations


def carregar_sql_curso():
    sql_curso = open('grade_horario/sql/cursos.sql', 'r').read()
    return sql_curso


def limpar_tabela_curso():
    return 'DELETE FROM grade_horario_cursos'


class Migration(migrations.Migration):

    dependencies = [
        ('grade_horario', '0005_CargaInicial_Dias'),
    ]

    operations = [
        migrations.RunSQL(carregar_sql_curso(), limpar_tabela_curso())
    ]
