# Generated by Django 2.1.2 on 2019-02-04 00:15

from django.db import migrations


def carregar_sql_disponibilidade():
    sql_disponibilidade = open('grade_horario/sql/disponibilidade.sql', 'r').read()
    return sql_disponibilidade


def limpar_tabela_disponibilidade():
    return 'DELETE FROM grade_horario_disponibilidades'


class Migration(migrations.Migration):

    dependencies = [
        ('grade_horario', '0007_CargaInicial_Disciplina'),
    ]

    operations = [
        migrations.RunSQL(carregar_sql_disponibilidade(), limpar_tabela_disponibilidade())
    ]
